version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A celery_worker worker --loglevel=info
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    command: celery -A celery_worker beat --loglevel=info
    depends_on:
      - redis
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
      - POSTGRES_HOST=localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  flower:
    build: .
    command: celery -A celery_worker flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker

volumes:
  postgres_data: